### ISSUE TITLE
BLE-MIDI incompatible with most recent version of Espressif ESP32 libraries, older version required to compile

### ISSUE THREAD

**Issue by gadevoi** [v0ss3n/midimadness#1]
A breaking change introduced to Espressif’s ESP32 BLE library in https://github.com/espressif/arduino-esp32/pull/8724 breaks compatibility with the BLE-MIDI library by lathoub, which hasn’t been updated since. This makes the code examples given that use BLE-MIDI unable to compile, such as the file [MIDI-madness-BLE-keyboard-constant-sending.ino](https://github.com/v0ss3n/midimadness/blob/main/Arduino%20(code)/MIDI-madness-BLE-keyboard-constant-sending/MIDI-madness-BLE-keyboard-constant-sending.ino). Instead of compiling, it gives an error  `Compilation error: conversion from 'String' to non-scalar type 'std::string' {aka 'std::__cxx11::basic_string'} requested`

This can be solved by downgrading the version of the board manager Espressif ESP32 in the Arduino IDE, for example to version `2.0.13`, in which the code compiles normally.

Screenshot showing the downgraded version 2.0.13 selected, and the code compiled without error:

<img width="1252" height="853" alt="Image" src="https://github.com/user-attachments/assets/3d77b3df-7f48-47fb-9db5-ef689675dd21" />
